### ISSUE TITLE
Editor configuration page missing title

### ISSUE THREAD

**Issue by adamzuckerman** [mohamicorp/editor-for-stash-issues#15]
I am using
- Stash version 3.9.1
- Editor For Stash version 1.4.1

The repository settings page for Editor does not have a title:
![editormissingtitle](https://cloud.githubusercontent.com/assets/6227944/8732418/ea74470c-2bc2-11e5-8bfe-77f21a841991.png)

All of the other settings for the repository have a title:
![repodetailsettingswithtitle](https://cloud.githubusercontent.com/assets/6227944/8732417/ea6f981a-2bc2-11e5-8564-e13bc025f5c9.png)

**Comment by mdavoodi** [comment]
This is fixed in release 1.5.
