### ISSUE TITLE
version history for 1.5.0.1 seems wrong

### ISSUE THREAD

**Issue by javaerb** [mohamicorp/editor-for-stash-issues#17]
Says it's for Stash 3.0.0 - 3.11.1. That does not seem right (unless it works for 3.11.x and not 3.10.x)

**Comment by mdavoodi** [comment]
Yeah that's right, it works for all Stash 3 versions except 3.10.X.

**Comment by javaerb** [comment]
and 1.5 works for 3.10 and 3.11?

**Comment by mdavoodi** [comment]
Yes, 1.5 works for both since it uses an api Atlassian added in 3.10.

**Comment by javaerb** [comment]
a bit confusing in the version history, but OK.
