### ISSUE TITLE
editing Pull Request from personal fork does not seem to work

### ISSUE THREAD

**Issue by javaerb** [mohamicorp/editor-for-stash-issues#18]
When I create a branch and PR within a repo, editing a file in the PR works OK. When I create a personal fork of the repo, and create a PR from my fork to the "original" repo, editing the file in the PR gives me a "500" error. (I have no restrictions on editing or pushing in my personal fork repo.)

This is 1.5.0.1

**Comment by javaerb** [comment]
I am referring to the "edit" pencil in the Diff view.

**Comment by mdavoodi** [comment]
It looks like Stash has a bug in which it redirects to the incorrect project if you click the source view button from a pull request that stems from a fork. I made an issue you can look at it [here](https://jira.atlassian.com/browse/STASH-7752). The edit button bases it's url off of the source view button, so this is the reason it's currently broken. 

We're going to wait for Atlassian to respond to the issue and see if they intend to fix it. If not, we'll code our way around it.

**Comment by ebukoski** [comment]
+1 our org ran into this today as well.  Exact same issue, resulted in a 500 message.

**Comment by mdavoodi** [comment]
We've fixed this issue in 1.5.2. Could you guys confirm its fixed?

**Comment by ebukoski** [comment]
I did a few tests and it worked for me.  Will post back if we find any more issues.

**Comment by mdavoodi** [comment]
Okay I'll go ahead and close this issue. Open a new one if you encounter a new issue.
