### ISSUE TITLE
Pull Request source branch should be an exception to direct push restriction

### ISSUE THREAD

**Issue by javaerb** [mohamicorp/editor-for-stash-issues#19]
Even if direct commit to branch is disabled, I would like to be able to 
- Edit a file in a PR
- Edit a different file on the PR source branch

Currently this is not possible.

**Comment by javaerb** [comment]
As a side note, the new enhanced Stash branch permissions seem to solve this, because if branch permissions are granular enough, the plugin option to disable direct branch commits could be unnecessary. But group workflows can be so different from each other.

**Comment by mdavoodi** [comment]
After some talk with the team, we don't think this is necessary since branch permissions seems to solve this. I'm going to close this issue.
