### ISSUE TITLE
When editing file from pull request, Commit directly to the branch should be only option

### ISSUE THREAD

**Issue by javaerb** [mohamicorp/editor-for-stash-issues#20]
When editing a file from the Pull Request view, it does not really make sense to have the option to create new PR.

**Comment by javaerb** [comment]
(depends on having enhancement #19)

**Comment by 304NotModified** [comment]
In some cases it isn't bad to create a PR for a PR. So I wouldn't remove it.

**Comment by mdavoodi** [comment]
I agree, going to close this issue.
