### ISSUE TITLE
Edit button in Pull Requests breaks diff view for Bitbucket 4.4.0

### ISSUE THREAD

**Issue by mdavoodi** [mohamicorp/editor-for-stash-issues#21]
Breaks the diff view for pull requests. Chrome, "Uncaught TypeError: Cannot read property 'split' of undefined batch.js:4131 Atlassian Stash v3.3.2

**Comment by tilmanschweitzer** [comment]
I have a similar problem and can not switch between diffs in the PR view.

Bitbucket-Version: 4.4.2
Plugin Version: 2.0.1

I took a look at the browser console and found this exception:

```
Uncaught TypeError: Cannot read property 'textContent' of undefined
    c.buildPullRequestUrl
    t
    WebFragments.addWebItemDescriptor.context-provider
    t
    (anonymous function)
    getWebFragments 
```

... which is caused by the following line:

```
var i = h(".ref.branch")[0].textContent
```

**Comment by tilmanschweitzer** [comment]
The element containing the branch name seems to be renamed to `jQuery('.ref-name-from .branch-name')`.

**Comment by mdavoodi** [comment]
It looks like this happened in the new Bitbucket update. Working on a fix right now.

**Comment by mdavoodi** [comment]
This is now fixed in the latest release. https://marketplace.atlassian.com/plugins/com.mohamicorp.stash.plugin.editor-for-stash/server/versionhistory

**Comment by tilmanschweitzer** [comment]
@mdavoodi Thanks for the really fast fix!
