### ISSUE TITLE
Edit button doesn't show up

### ISSUE THREAD

**Issue by rccoe** [mohamicorp/editor-for-stash-issues#23]
Console error: "EditorForStash is not defined"
Trace: https://gist.github.com/rccoe/50256f39a474121fdd81

Stash 3.8.0
Chrome 44.0.2403.157

**Comment by mdavoodi** [comment]
Could you give the Editor for Stash version and describe the page this happening on? Is it the pull request view or the source view? Could you also send your server logs?

**Comment by rccoe** [comment]
Editor for Stash 1.5.1
It's happening on the source view
The logs are really short and don't contain any references to the plugin or the issue I saw

**Comment by mdavoodi** [comment]
Ive pulled 1.5.1 from the marketplace. Downgrade to 1.5.0.1 until we resolve the issue.

**Comment by mdavoodi** [comment]
Hey rccoe, could you see if 1.5.2 fixed the issue you we're seeing?

**Comment by rccoe** [comment]
It looks like this resolved the issue. Thank you!

On Mon, Sep 28, 2015 at 11:11 PM, Mohammed Davoodi <notifications@github.com
