### ISSUE TITLE
Support for BitBucket Server 4.0 ?

### ISSUE THREAD

**Issue by ebukoski** [mohamicorp/editor-for-stash-issues#26]
BitBucket Server 4.0 (previously known as Stash) is coming:

https://confluence.atlassian.com/bitbucketserver/bitbucket-rebrand-faq-779298912.html

Are you planning on migrating Editor For Stash to BitBucket 4.0 Server?

**Comment by mdavoodi** [comment]
Yes. A build will be out in a few days with a few bug fixes as well.

**Comment by mdavoodi** [comment]
4.0 support has been added in 2.0. Check out our marketplace page.
