### ISSUE TITLE
Add ability to create new files

### ISSUE THREAD

**Issue by 304NotModified** [mohamicorp/editor-for-stash-issues#30]
I can edit a file, but how do I create a new file? 

Bitbucket server v4.2.0

**Comment by mdavoodi** [comment]
Currently the editor does not support creating new files. You can only edit created files. We are interested in implementing this feature and is the next feature on our roadmap.

**Comment by 304NotModified** [comment]
Great to hear! Thanks for the feedback!

**Comment by mdavoodi** [comment]
Adding new files is now supported in version 2.3 of the plugin.

**Comment by 304NotModified** [comment]
\0/
