### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by 304NotModified** [mohamicorp/editor-for-stash-issues#31]
Is there a way to boost the performance? 

Editing a file (small, 5 lines), takes around 9 secs (time between press edit button and interface loaded)

**Comment by mdavoodi** [comment]
We've received another report of the editor taking some time to load, even though browsing to that file originally happened quickly. Going to look into this more.

**Comment by mdavoodi** [comment]
This is now fixed in [version 2.2](https://marketplace.atlassian.com/plugins/com.mohamicorp.stash.plugin.editor-for-stash/versions).

**Comment by mdavoodi** [comment]
Let me know if you don't see any performance improvements.
