### ISSUE TITLE
Need search functionality

### ISSUE THREAD

**Issue by airdeck** [mohamicorp/editor-for-stash-issues#33]
It would be great to implement some sort of search feature. With some larger files (usually large due to content) it would be a big improvement if you could search on a file when it is open in the editor. The in-browser search, at least in Chrome on OS X, doesn't seem to search the whole document.

**Comment by mdavoodi** [comment]
We've heard this feedback before, it shouldn't be too hard to fix. We can probably roll this in to the next update.

**Comment by airdeck** [comment]
That's great to hear, thanks @mdavoodi! When do you expect the next update to roll out?

**Comment by mdavoodi** [comment]
Don't have an ETA as of now, I'll talk to the team and get back to you.

**Comment by mdavoodi** [comment]
This feature is now available in Editor for Bitbucket (Stash) 2.1. Please check it out and let me know if you have any feedback.

Here's a [link](https://marketplace.atlassian.com/plugins/com.mohamicorp.stash.plugin.editor-for-stash/versions).
