### ISSUE TITLE
Add ability to configure Tab key behavior

### ISSUE THREAD

**Issue by florianbehrens** [mohamicorp/editor-for-stash-issues#36]
Currently the Tab key only seems to produce a horizontal tab (ASCII 0x09) character. The ability to change that to a configurable amount of space characters (ASCII 0x20) would be fine.

**Comment by mdavoodi** [comment]
Shouldn't be too hard to do.

**Comment by mdavoodi** [comment]
This has been added in version [2.5](https://marketplace.atlassian.com/plugins/com.mohamicorp.stash.plugin.editor-for-stash/server/versionhistory) of the plugin.
