### ISSUE TITLE
Enable disable direct commits on a global level

### ISSUE THREAD

**Issue by mdavoodi** [mohamicorp/editor-for-stash-issues#38]

**Comment by ticapix** [comment]
That would a very good feature to allow non-technical people to easily create PR for small/minor changes (in doc, readme, translation strings, ...)

**Comment by mdavoodi** [comment]
Had a second request for this feature today via email.

**Comment by mdavoodi** [comment]
This has been implemented in the latest release. You can find it [here](https://marketplace.atlassian.com/manage/plugins/com.mohamicorp.stash.plugin.editor-for-stash/versions).
