### ISSUE TITLE
Ability to edit merge conflict in Bitbucket

### ISSUE THREAD

**Issue by jmodi1982** [mohamicorp/editor-for-stash-issues#45]
Hi, 

Since we want to use Bitbucket for code review and merge the changes to destination branch, it is advisable to  provide a capability to reviewer to edit the merge commit and checkin the code. 

Without this capability the plugin does not help us in completing the code review process. 

You can create a configuration option to turn this ON at repository level so that any repos not following the Bitbucket or git flow branching model can also make use of this plugin.

Thanks,
Jeemish

**Comment by mdavoodi** [comment]
We still need to take a look at how much effort this would be to integrate, but I agree this would be a valuable feature.

**Comment by jmodi1982** [comment]
Hi,

Any idea on when this enhancement would be done ? We have already bought this plugin for our Jira instance

**Comment by mdavoodi** [comment]
We can't currently give you a specific timeline, but we're currently working on an update to be able to delete and rename files, so this would come after that.

**Comment by jmodi1982** [comment]
Hi, we do not need a specific date for the fix, atleast can you give a high level estimated date (2weeks/1 month) when you might be able to do it.

**Comment by jmodi1982** [comment]
Hi, we do not need a specific date for the fix, atleast can you give a high level estimated date (2weeks/1 month) when you might be able to do it.

**Comment by mdavoodi** [comment]
Unfortunately our company policy is to not publicly comment on release dates for new features. I cannot give you a specific timeline, but I can say it is currently in development.

Mohammed

**Comment by jmodi1982** [comment]
Thanks Mohammed, will wait for further communication on the release

**Comment by jmodi1982** [comment]
Hi Mohamed,

Any update on the issue ?

Thanks,
Jeemish

**Comment by jmodi1982** [comment]
Hi Mohamed,

Any update on the issue ?

Thanks,
Jeemish

**Comment by jmodi1982** [comment]
Hi Mohamed,

Any update on the issue ? 

Thanks,
Jeemish

**Comment by jmodi1982** [comment]
Hi Mohamed,

It would be great if you can give us an update on this issue, it is becoming critical for us. 

Appreciate all the help.

Thanks,
Jeemish

**Comment by jmodi1982** [comment]
Hi Mohamed,

It would be great if you can give us an update on this issue, it is becoming critical for us.

Thanks,
Jeemish

**Comment by jmodi1982** [comment]
@mdavoodi 

Hi Mohamed,

It would be great if you can give us an update on this issue, it is becoming critical for us.

Thanks,
Jeemish

**Comment by jmodi1982** [comment]
@mdavoodi 

Hi Mohamed,

It is getting close to 3 months now since we opened this request. Any update on when we should expect this fixed? Without this feature, the plugin has limited use to us.

Thanks,
Jeemish

**Comment by jmodi1982** [comment]
@mdavoodi 

Hi Mohamed,

It is getting close to 4 months now since we opened this request. Any update on when we should expect this fixed? Without this feature, the plugin has limited use to us.

Thanks,
Jeemish

**Comment by mdavoodi** [comment]
@jmodi1982 this has been added in [version 2.6](https://marketplace.atlassian.com/plugins/com.mohamicorp.stash.plugin.editor-for-stash/server/versionhistory) :)

**Comment by jmodi1982** [comment]
@mdavoodi The implementation of resolve conflicts is not the way which Git recommends. We wanted the ability to edit the merge commit on the destination branch and not make a new commit on source branch itself. Please can you look at the "Basic Merge Conflicts" section on the page https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

I would be happy to discuss over call also if you need more info.

Thanks,
Jeemish

**Comment by mdavoodi** [comment]
I made a new issue to track your question #54. Lets move the discussion there.

**Comment by RaduTudorIon** [comment]
It's 2020, when will this be implemented?
