### ISSUE TITLE
Add possibility to deactive direct commit globally

### ISSUE THREAD

**Issue by pyriand3r** [mohamicorp/editor-for-stash-issues#47]
Great plugin, but configuring every single repository to prevent direct commits and force pull request is hell of a work (if you have tons of repos like we have).
It would be great if it would be possible to deactive direct commit globally, so you don't have to disable it in every single repository.

**Comment by mdavoodi** [comment]
I agree, that's why this feature was already implemented and released two days ago! Check out the latest version of the plugin.
