### ISSUE TITLE
Disable direct commit , but only to certain branches. 

### ISSUE THREAD

**Issue by mdavoodi** [mohamicorp/editor-for-stash-issues#5]
We use a model where we allow commits/pushes only to non-integration branches.  I would like for people to be able to edit branches during a review, but not the integration branch. 

Our integration branches have the following names/patterns 

master 
develop\* 
eco??-????

**Comment by javaerb** [comment]
I thing this is better addressed with a separate Stash plugin (or improvements in Stash), as it is a general issue beyond this plugin.

**Comment by mdavoodi** [comment]
I agree, marking this as closed.
