### ISSUE TITLE
Rename should include not just the file name, but the full path.

### ISSUE THREAD

**Issue by mdavoodi** [mohamicorp/editor-for-stash-issues#51]
Right now if you try and rename a file in a folder, it will place the file in the root directory since only the filename is being populated in the directory.

**Comment by AndreyLevchenko** [comment]
if path is specified file is moved
otherwise it's renamed in current folder
what is wrong behavior?

**Comment by mdavoodi** [comment]
This has been fixed in Power Editor for Bitbucket, version [2.6](https://marketplace.atlassian.com/plugins/com.mohamicorp.stash.plugin.editor-for-stash/server/versionhistory)
