### ISSUE TITLE
Add upload button

### ISSUE THREAD

**Issue by mdavoodi** [mohamicorp/editor-for-stash-issues#53]

**Comment by KrayzeeKev** [comment]
In relation to our discussion on the Atlassian forums, what we're after is simply the ability for a web-based user to upload a file into a repo and have it committed. Regardless of file type. Upload and click "commit". Simple :-) Right now, our proposed solution is to build an entire website to take the file upload and then do:
git clone
cd repo
cp /tmp/uploadfile .
git add .
git commit -m "Update at `date`"
git push
cd ..
rm -rf repo

Seem a bit over the top to just update a file in a repo. So I'm searching for solutions.

**Comment by mdavoodi** [comment]
@KrayzeeKev would like to let you know that this is now under development and we're entering the first stage of testing!

**Comment by mdavoodi** [comment]
This is now a feature in 2.7.
