### ISSUE TITLE
Resolve Merge Conflicts does not follow recommended merge protocol

### ISSUE THREAD

**Issue by mdavoodi** [mohamicorp/editor-for-stash-issues#54]
> The implementation of resolve conflicts is not the way which Git recommends. We wanted the ability to edit the merge commit on the destination branch and not make a new commit on source branch itself. Please can you look at the "Basic Merge Conflicts" section on the page https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging
> 
> I would be happy to discuss over call also if you need more info.

Here is how a merge should be done:

**Before merge:**
branch-with-changes
**ab2md4m** My commit 

master
**bh6dsd** conflicting commit

**After resolve conflicts:**
branch-with-changes
**ab2md4m** My commit 

master
**bh6dsd+ab2md4m** M Merged branch branch-with-changes
**bh6dsd** conflicting commit
**ab2md4m** My commit 

Everything is now merged.

But here is what it currently looks like:

**Before merge:**
branch-with-changes
**ab2md4m** My commit 

master
**bh6dsd** conflicting commit

**After merge:**
branch-with-changes
**bh6dsd+ab2md4m** M Merged branch branch-with-changes
**bh6dsd** conflicting commit
**ab2md4m** My commit 

master
**bh6dsd** conflicting commit
**ab2md4m** My commit 

Now you have to merge again from the UI so you get something like this:

branch-with-changes
**bh6dsd+ab2md4m** M Merged branch branch-with-changes
**bh6dsd** conflicting commit
**ab2md4m** My commit 

master
**6ksadad3** Merged branch
**bh6dsd+ab2md4m** M Merged branch branch-with-changes
**bh6dsd** conflicting commit
**ab2md4m** My commit

**Comment by jmodi1982** [comment]
@mdavoodi The implementation of resolve conflicts is not the way which Git recommends. We wanted the ability to edit the merge commit on the destination branch and not make a new commit on source branch itself. Please can you look at the "Basic Merge Conflicts" section on the page https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

I would be happy to discuss over call also if you need more info.

Our decision to renew the plugin depends on this feature, so please can you confirm how we can get this feature enabled into the plugin.

Thanks,
Jeemish

**Comment by jmodi1982** [comment]
@mdavoodi any update on the issue i reported above. This is holding off our decision to renew the license for this plugin. Hence please provide an update

**Comment by mdavoodi** [comment]
Hello @jmodi1982 , please send us your license number to verify you're a customer. You can email it to support@mohamicorp.com. We still haven't had time to review the implementation details, but we consider this request lower priority because the plugin still delivers the functionality just not in the way that you desire.

**Comment by mdavoodi** [comment]
Another report

Yesterday i tried to use the „resolved conflicts“ feature from a pull-request…
 
![image](https://cloud.githubusercontent.com/assets/2616497/23734241/a924a324-0432-11e7-821f-23bd2dc1a2e6.png)


 
 
Here the conflicted file
![image](https://cloud.githubusercontent.com/assets/2616497/23734244/ad7c06ec-0432-11e7-882a-8ee8884d010e.png)

 
But there is no way to resolve the conflict. The right pane is empty, even when i click on file_tsc2.txt in the left pane. What am i missing/doing wrong?
![image](https://cloud.githubusercontent.com/assets/2616497/23734247/b52c96f4-0432-11e7-9616-f686289cd025.png)

**Comment by mdavoodi** [comment]
This is fixed in Power Editor for [Bitbucket 2.6.1](https://marketplace.atlassian.com/plugins/com.mohamicorp.stash.plugin.editor-for-stash/server/versionhistory).
