### ISSUE TITLE
Disable Direct Commit entirely on projects basis

### ISSUE THREAD

**Issue by atruelsen** [mohamicorp/editor-for-stash-issues#55]
Hi

We need to be able to enable Power Editor entirely on a project basis to allow project admins to opt-in if they want that functionality.
Until such a feature is implemented I cannot enable Power Editor on my Bitbucket server.

regards
/anders

**Comment by mdavoodi** [comment]
This should be easy to add, though I can't give you an exact timeframe.

**Comment by atruelsen** [comment]
That's cool.
I hope you find the time one day :-)

Regards
/anders
tor. 23. feb. 2017 kl. 20.29 skrev Mohammed Davoodi <
notifications@github.com>:

**Comment by mdavoodi** [comment]
This is now implemented in version 2.6.3 of the plugin :)

https://marketplace.atlassian.com/plugins/com.mohamicorp.stash.plugin.editor-for-stash/server/versionhistory
