### ISSUE TITLE
Resolve conflicts in PR stays empty

### ISSUE THREAD

**Issue by MHaendel** [mohamicorp/editor-for-stash-issues#56]
Hey,

if I do a PR which has conflicts and I try to merge them on web I get the Editor `Resolve conflicts` which lists the files that needs merging, but the content is empty. Theres no error showing up in debug log nor in webdev panel.

**Comment by mdavoodi** [comment]
Do you mind sending me a screenshot of what the diff view for the PR shows and what the editor is showing? You can send it to support@mohamicorp.com so you don't share proprietary information.

**Comment by mdavoodi** [comment]
Ping.

**Comment by mdavoodi** [comment]
Another report

Yesterday i tried to use the „resolved conflicts“ feature from a pull-request…
 
![image](https://cloud.githubusercontent.com/assets/2616497/23734241/a924a324-0432-11e7-821f-23bd2dc1a2e6.png)


 
 
Here the conflicted file
![image](https://cloud.githubusercontent.com/assets/2616497/23734244/ad7c06ec-0432-11e7-882a-8ee8884d010e.png)

 
But there is no way to resolve the conflict. The right pane is empty, even when i click on file_tsc2.txt in the left pane. What am i missing/doing wrong?
![image](https://cloud.githubusercontent.com/assets/2616497/23734247/b52c96f4-0432-11e7-9616-f686289cd025.png)

**Comment by mdavoodi** [comment]
This is fixed in Power Editor for [Bitbucket 2.6.1](https://marketplace.atlassian.com/plugins/com.mohamicorp.stash.plugin.editor-for-stash/server/versionhistory).
