### ISSUE TITLE
Editor changes all line endings to UNIX style

### ISSUE THREAD

**Issue by mdavoodi** [mohamicorp/editor-for-stash-issues#57]
It’s converting all line endings from Windows style CRLF to Unix CR.

It should detect what the line endings are and stick with that.

**Comment by highlandery** [comment]
Thanks Mohammed, appreciate you looking into it.

**Comment by mdavoodi** [comment]
This is fixed in Power Editor for [Bitbucket 2.6.1](https://marketplace.atlassian.com/plugins/com.mohamicorp.stash.plugin.editor-for-stash/server/versionhistory).
