### ISSUE TITLE
Limit edit access to specific Users / Folders /Files

### ISSUE THREAD

**Issue by rccoe** [mohamicorp/editor-for-stash-issues#7]
Would this be possible? It would be a great way to allow operations people to quickly edit a few files in an otherwise private repo.

**Comment by mdavoodi** [comment]
This would involve writing a permissions database of our own instead of using stash's built in permissions. It's definitely doable but would require a lot of effort. We'll consider this if we see a lot more interest.

**Comment by ebukoski** [comment]
My company has a similar need to restrict editing.  Would it be possible to disable editing on a per project or per repo basis?

**Comment by mdavoodi** [comment]
Stash's general permissions allow access to be disabled unless a user has project or repository permissions. Those same permissions apply to editing.

This issue is talking about limiting permissions further then that to file and folder permissions which is not supported by stash.

**Comment by mdavoodi** [comment]
After more thought we decided that edit permissions for specific files should be handled by stash, instead of in this plugin.
