### ISSUE TITLE
Is there any separate editor plugins available for BitBucket cloud hosting and on-premise hosting?

### ISSUE THREAD

**Issue by Venkattk** [mohamicorp/editor-for-stash-issues#71]
Hi,

I am trying to experience this power editor plugin. I am using the BitBucket cloud version. While trying to download the editor plugin community edition, it says "This hosting is not available for this add-on". Kindly clarify whether the server version can be used for the clouse hosting too?

If the same plugin to be used for both server and cloud hosting, please detail the steps for configuring the plugin in BitBucket cloud hosting.

**Comment by mdavoodi** [comment]
Hi Venkattk,

Unfortunately the plugin can only be used for server, there is currently no cloud support.

Mohammed
