### ISSUE TITLE
Project rows expand/colapseable

### ISSUE THREAD

**Issue by mdavoodi** [mohamicorp/editor-for-stash-issues#77]
Another cool thing would be making the projects close/expandable by default. That would help users with a very large amount of projects/repositories.

**Comment by AndreyLevchenko** [comment]
@mdavoodi 
my current pagination imlementation ensures that there are only 20 repositories on page. So I think making it collapseable is not required. And even may lead to strange results as those 20 repos can be distrubuted among project by different ways

**Comment by mdavoodi** [comment]
You're right, didn't think about that. I'll close this.
